'use strict';

/**
 * Task 16 — Notifications + WebSockets Enums, Taxonomy, and Constants
 */

const NOTIFICATION_TYPES = Object.freeze({
  INCIDENT_CREATED: 'INCIDENT_CREATED',
  INCIDENT_UPDATED: 'INCIDENT_UPDATED',
  INCIDENT_SEVERITY_CHANGED: 'INCIDENT_SEVERITY_CHANGED',

  INVESTIGATION_STARTED: 'INVESTIGATION_STARTED',
  INVESTIGATION_COMPLETED: 'INVESTIGATION_COMPLETED',
  INVESTIGATION_FAILED: 'INVESTIGATION_FAILED',

  RECOVERY_PLAN_CREATED: 'RECOVERY_PLAN_CREATED',
  RECOVERY_APPROVAL_REQUIRED: 'RECOVERY_APPROVAL_REQUIRED',

  APPROVAL_GRANTED: 'APPROVAL_GRANTED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  APPROVAL_EXPIRED: 'APPROVAL_EXPIRED',

  RECOVERY_STARTED: 'RECOVERY_STARTED',
  RECOVERY_COMPLETED: 'RECOVERY_COMPLETED',
  RECOVERY_FAILED: 'RECOVERY_FAILED',

  VERIFICATION_STARTED: 'VERIFICATION_STARTED',
  VERIFICATION_COMPLETED: 'VERIFICATION_COMPLETED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  VERIFICATION_INCONCLUSIVE: 'VERIFICATION_INCONCLUSIVE',

  PERSISTENCE_DETECTED: 'PERSISTENCE_DETECTED',
  REINVESTIGATION_TRIGGERED: 'REINVESTIGATION_TRIGGERED',

  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  INCIDENT_REMAINED_UNRESOLVED: 'INCIDENT_REMAINED_UNRESOLVED',

  CRITICAL_SECURITY_EVENT: 'CRITICAL_SECURITY_EVENT',
});

const NOTIFICATION_SEVERITIES = Object.freeze({
  INFO: 'INFO',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
});

const WS_INBOUND_TYPES = Object.freeze({
  PING: 'PING',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATIONS_READ_ALL: 'NOTIFICATIONS_READ_ALL',
});

const WS_OUTBOUND_TYPES = Object.freeze({
  PONG: 'PONG',
  NOTIFICATION: 'NOTIFICATION',
  CONNECTED: 'CONNECTED',
  ERROR: 'ERROR',
});

const WS_CONNECTION_STATES = Object.freeze({
  CONNECTING: 'CONNECTING',
  AUTHENTICATING: 'AUTHENTICATING',
  CONNECTED: 'CONNECTED',
  DISCONNECTING: 'DISCONNECTING',
  DISCONNECTED: 'DISCONNECTED',
});

const NOTIFICATION_AUDIT_ACTIONS = Object.freeze({
  WEBSOCKET_CONNECTED: 'WEBSOCKET_CONNECTED',
  WEBSOCKET_AUTH_FAILED: 'WEBSOCKET_AUTH_FAILED',
  WEBSOCKET_DISCONNECTED: 'WEBSOCKET_DISCONNECTED',
  NOTIFICATION_CREATED: 'NOTIFICATION_CREATED',
  NOTIFICATION_DELIVERED: 'NOTIFICATION_DELIVERY',
  NOTIFICATION_DELIVERY_FAILED: 'NOTIFICATION_DELIVERY_FAILED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  NOTIFICATION_READ_ALL: 'NOTIFICATION_READ_ALL',
});

module.exports = {
  NOTIFICATION_TYPES,
  NOTIFICATION_SEVERITIES,
  WS_INBOUND_TYPES,
  WS_OUTBOUND_TYPES,
  WS_CONNECTION_STATES,
  NOTIFICATION_AUDIT_ACTIONS,
};

