'use strict';

/**
 * Canonical Event Taxonomy, Categories, and Normalization Constants for Re:COVER.
 */

const EVENT_CATEGORIES = Object.freeze({
  AUTHENTICATION_EVENT: 'AUTHENTICATION_EVENT',
  SECURITY_EVENT: 'SECURITY_EVENT',
  ACCOUNT_CHANGE: 'ACCOUNT_CHANGE',
  CREDENTIAL_CHANGE: 'CREDENTIAL_CHANGE',
  REPOSITORY_ACTIVITY: 'REPOSITORY_ACTIVITY',
  OAUTH_ACTIVITY: 'OAUTH_ACTIVITY',
  DEVICE_EVENT: 'DEVICE_EVENT',
});

const CANONICAL_EVENT_CATEGORIES_LIST = Object.values(EVENT_CATEGORIES);

const EVENT_TYPES = Object.freeze({
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SUSPICIOUS_LOGIN: 'SUSPICIOUS_LOGIN',
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_TERMINATED: 'SESSION_TERMINATED',
  OAUTH_GRANTED: 'OAUTH_GRANTED',
  OAUTH_REVOKED: 'OAUTH_REVOKED',
  TOKEN_CREATED: 'TOKEN_CREATED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  SECURITY_SETTING_CHANGED: 'SECURITY_SETTING_CHANGED',
  ACCOUNT_SETTING_CHANGED: 'ACCOUNT_SETTING_CHANGED',
  DEVICE_ADDED: 'DEVICE_ADDED',
  DEVICE_REMOVED: 'DEVICE_REMOVED',
  SSH_KEY_CREATED: 'SSH_KEY_CREATED',
  SSH_KEY_REMOVED: 'SSH_KEY_REMOVED',
  REPOSITORY_ACCESS: 'REPOSITORY_ACCESS',
  REPOSITORY_ACTIVITY: 'REPOSITORY_ACTIVITY',
  UNKNOWN: 'UNKNOWN',
});

const CANONICAL_EVENT_TYPES_LIST = Object.values(EVENT_TYPES);

const SEVERITIES = Object.freeze({
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  INFO: 'INFO',
});

const CANONICAL_SEVERITIES_LIST = Object.values(SEVERITIES);

const EVENT_STATUSES = Object.freeze({
  RAW: 'RAW',
  NORMALIZED: 'NORMALIZED',
  ANALYZED: 'ANALYZED',
  CORRELATED: 'CORRELATED',
  DISMISSED: 'DISMISSED',
});

const CANONICAL_STATUSES_LIST = Object.values(EVENT_STATUSES);

const PROVIDERS = Object.freeze({
  GOOGLE: 'GOOGLE',
  GITHUB: 'GITHUB',
  AWS: 'AWS',
});

const CANONICAL_PROVIDERS_LIST = Object.values(PROVIDERS);

/**
 * Baseline default severity mappings for canonical event types.
 */
const DEFAULT_SEVERITY_BY_EVENT_TYPE = Object.freeze({
  [EVENT_TYPES.SUSPICIOUS_LOGIN]: SEVERITIES.HIGH,
  [EVENT_TYPES.SECURITY_SETTING_CHANGED]: SEVERITIES.HIGH,
  [EVENT_TYPES.SSH_KEY_CREATED]: SEVERITIES.HIGH,
  [EVENT_TYPES.SSH_KEY_REMOVED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.TOKEN_CREATED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.TOKEN_REVOKED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.OAUTH_GRANTED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.OAUTH_REVOKED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.DEVICE_ADDED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.DEVICE_REMOVED]: SEVERITIES.LOW,
  [EVENT_TYPES.SESSION_CREATED]: SEVERITIES.INFO,
  [EVENT_TYPES.SESSION_TERMINATED]: SEVERITIES.INFO,
  [EVENT_TYPES.LOGIN]: SEVERITIES.INFO,
  [EVENT_TYPES.LOGOUT]: SEVERITIES.INFO,
  [EVENT_TYPES.ACCOUNT_SETTING_CHANGED]: SEVERITIES.LOW,
  [EVENT_TYPES.REPOSITORY_ACCESS]: SEVERITIES.LOW,
  [EVENT_TYPES.REPOSITORY_ACTIVITY]: SEVERITIES.LOW,
  [EVENT_TYPES.UNKNOWN]: SEVERITIES.INFO,
});

/**
 * Maps canonical event types to standard event categories.
 */
const EVENT_CATEGORY_BY_EVENT_TYPE = Object.freeze({
  [EVENT_TYPES.LOGIN]: EVENT_CATEGORIES.AUTHENTICATION_EVENT,
  [EVENT_TYPES.LOGOUT]: EVENT_CATEGORIES.AUTHENTICATION_EVENT,
  [EVENT_TYPES.SUSPICIOUS_LOGIN]: EVENT_CATEGORIES.AUTHENTICATION_EVENT,
  [EVENT_TYPES.SESSION_CREATED]: EVENT_CATEGORIES.AUTHENTICATION_EVENT,
  [EVENT_TYPES.SESSION_TERMINATED]: EVENT_CATEGORIES.AUTHENTICATION_EVENT,

  [EVENT_TYPES.SECURITY_SETTING_CHANGED]: EVENT_CATEGORIES.SECURITY_EVENT,
  [EVENT_TYPES.ACCOUNT_SETTING_CHANGED]: EVENT_CATEGORIES.ACCOUNT_CHANGE,

  [EVENT_TYPES.SSH_KEY_CREATED]: EVENT_CATEGORIES.CREDENTIAL_CHANGE,
  [EVENT_TYPES.SSH_KEY_REMOVED]: EVENT_CATEGORIES.CREDENTIAL_CHANGE,
  [EVENT_TYPES.TOKEN_CREATED]: EVENT_CATEGORIES.CREDENTIAL_CHANGE,
  [EVENT_TYPES.TOKEN_REVOKED]: EVENT_CATEGORIES.CREDENTIAL_CHANGE,

  [EVENT_TYPES.OAUTH_GRANTED]: EVENT_CATEGORIES.OAUTH_ACTIVITY,
  [EVENT_TYPES.OAUTH_REVOKED]: EVENT_CATEGORIES.OAUTH_ACTIVITY,

  [EVENT_TYPES.DEVICE_ADDED]: EVENT_CATEGORIES.DEVICE_EVENT,
  [EVENT_TYPES.DEVICE_REMOVED]: EVENT_CATEGORIES.DEVICE_EVENT,

  [EVENT_TYPES.REPOSITORY_ACCESS]: EVENT_CATEGORIES.REPOSITORY_ACTIVITY,
  [EVENT_TYPES.REPOSITORY_ACTIVITY]: EVENT_CATEGORIES.REPOSITORY_ACTIVITY,

  [EVENT_TYPES.UNKNOWN]: EVENT_CATEGORIES.SECURITY_EVENT,
});

/**
 * Normalizes an arbitrary string into a canonical event type or UNKNOWN.
 *
 * @param {string} rawType
 * @returns {string}
 */
function normalizeEventType(rawType) {
  if (!rawType || typeof rawType !== 'string') return EVENT_TYPES.UNKNOWN;
  const upper = rawType.toUpperCase().trim();
  if (CANONICAL_EVENT_TYPES_LIST.includes(upper)) {
    return upper;
  }
  return EVENT_TYPES.UNKNOWN;
}

/**
 * Returns the canonical event category for a given event type.
 *
 * @param {string} eventType
 * @returns {string}
 */
function getEventCategory(eventType) {
  const normalized = normalizeEventType(eventType);
  return EVENT_CATEGORY_BY_EVENT_TYPE[normalized] || EVENT_CATEGORIES.SECURITY_EVENT;
}

module.exports = {
  EVENT_CATEGORIES,
  CANONICAL_EVENT_CATEGORIES_LIST,
  EVENT_TYPES,
  CANONICAL_EVENT_TYPES_LIST,
  SEVERITIES,
  CANONICAL_SEVERITIES_LIST,
  EVENT_STATUSES,
  CANONICAL_STATUSES_LIST,
  PROVIDERS,
  CANONICAL_PROVIDERS_LIST,
  DEFAULT_SEVERITY_BY_EVENT_TYPE,
  EVENT_CATEGORY_BY_EVENT_TYPE,
  normalizeEventType,
  getEventCategory,
};
