'use strict';

/**
 * Canonical Event Taxonomy and Normalization Constants for Re:COVER.
 */

const EVENT_TYPES = Object.freeze({
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_TERMINATED: 'SESSION_TERMINATED',
  OAUTH_GRANTED: 'OAUTH_GRANTED',
  OAUTH_REVOKED: 'OAUTH_REVOKED',
  TOKEN_CREATED: 'TOKEN_CREATED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  SECURITY_SETTING_CHANGED: 'SECURITY_SETTING_CHANGED',
  ACCOUNT_SETTING_CHANGED: 'ACCOUNT_SETTING_CHANGED',
  DEVICE_ADDED: 'DEVICE_ADDED',
  DEVICE_REMOVED: 'DEVICE_REMOVED',
  SSH_KEY_CREATED: 'SSH_KEY_CREATED',
  SSH_KEY_REMOVED: 'SSH_KEY_REMOVED',
  REPOSITORY_ACCESS: 'REPOSITORY_ACCESS',
  UNKNOWN: 'UNKNOWN',
});

const CANONICAL_EVENT_TYPES_LIST = Object.values(EVENT_TYPES);

const SEVERITIES = Object.freeze({
  CRITICAL: 'CRITICAL',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  INFO: 'INFO',
});

const CANONICAL_SEVERITIES_LIST = Object.values(SEVERITIES);

const EVENT_STATUSES = Object.freeze({
  RAW: 'RAW',
  NORMALIZED: 'NORMALIZED',
  ANALYZED: 'ANALYZED',
  CORRELATED: 'CORRELATED',
  DISMISSED: 'DISMISSED',
});

const CANONICAL_STATUSES_LIST = Object.values(EVENT_STATUSES);

const PROVIDERS = Object.freeze({
  GOOGLE: 'GOOGLE',
  GITHUB: 'GITHUB',
  AWS: 'AWS',
});

const CANONICAL_PROVIDERS_LIST = Object.values(PROVIDERS);

/**
 * Baseline default severity mappings for canonical event types.
 */
const DEFAULT_SEVERITY_BY_EVENT_TYPE = Object.freeze({
  [EVENT_TYPES.SECURITY_SETTING_CHANGED]: SEVERITIES.HIGH,
  [EVENT_TYPES.SSH_KEY_CREATED]: SEVERITIES.HIGH,
  [EVENT_TYPES.SSH_KEY_REMOVED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.TOKEN_CREATED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.TOKEN_REVOKED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.OAUTH_GRANTED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.OAUTH_REVOKED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.DEVICE_ADDED]: SEVERITIES.MEDIUM,
  [EVENT_TYPES.DEVICE_REMOVED]: SEVERITIES.LOW,
  [EVENT_TYPES.SESSION_CREATED]: SEVERITIES.INFO,
  [EVENT_TYPES.SESSION_TERMINATED]: SEVERITIES.INFO,
  [EVENT_TYPES.LOGIN]: SEVERITIES.INFO,
  [EVENT_TYPES.LOGOUT]: SEVERITIES.INFO,
  [EVENT_TYPES.ACCOUNT_SETTING_CHANGED]: SEVERITIES.LOW,
  [EVENT_TYPES.REPOSITORY_ACCESS]: SEVERITIES.LOW,
  [EVENT_TYPES.UNKNOWN]: SEVERITIES.INFO,
});

/**
 * Normalizes an arbitrary string into a canonical event type or UNKNOWN.
 *
 * @param {string} rawType
 * @returns {string}
 */
function normalizeEventType(rawType) {
  if (!rawType || typeof rawType !== 'string') return EVENT_TYPES.UNKNOWN;
  const upper = rawType.toUpperCase().trim();
  if (CANONICAL_EVENT_TYPES_LIST.includes(upper)) {
    return upper;
  }
  return EVENT_TYPES.UNKNOWN;
}

module.exports = {
  EVENT_TYPES,
  CANONICAL_EVENT_TYPES_LIST,
  SEVERITIES,
  CANONICAL_SEVERITIES_LIST,
  EVENT_STATUSES,
  CANONICAL_STATUSES_LIST,
  PROVIDERS,
  CANONICAL_PROVIDERS_LIST,
  DEFAULT_SEVERITY_BY_EVENT_TYPE,
  normalizeEventType,
};

