'use strict';

const { Annotation } = require('@langchain/langgraph');

/**
 * InvestigationStateAnnotation — Typed state definition for Re:COVER AI investigation graph.
 *
 * Tracks:
 * - Loaded incident context & initial Task 9 findings
 * - Investigation plan generated by Planner
 * - Accumulated tool calls and sanitized tool results
 * - Discovered observations, correlations, and evidence gaps
 * - Verifier results and final conclusions
 * - Bounded step counts and limits
 */
const InvestigationState = Annotation.Root({
  incidentId: Annotation({ reducer: (x, y) => y ?? x, default: () => '' }),
  userId: Annotation({ reducer: (x, y) => y ?? x, default: () => '' }),
  connectedAccountId: Annotation({ reducer: (x, y) => y ?? x, default: () => null }),
  incident: Annotation({ reducer: (x, y) => y ?? x, default: () => null }),
  evidence: Annotation({ reducer: (x, y) => y ?? x, default: () => [] }),
  plan: Annotation({ reducer: (x, y) => y ?? x, default: () => null }),
  toolCalls: Annotation({ reducer: (x, y) => [...(x || []), ...(y || [])], default: () => [] }),
  toolResults: Annotation({ reducer: (x, y) => [...(x || []), ...(y || [])], default: () => [] }),
  observations: Annotation({ reducer: (x, y) => [...(x || []), ...(y || [])], default: () => [] }),
  correlations: Annotation({ reducer: (x, y) => [...(x || []), ...(y || [])], default: () => [] }),
  evidenceGaps: Annotation({ reducer: (x, y) => [...(x || []), ...(y || [])], default: () => [] }),
  conclusions: Annotation({ reducer: (x, y) => y ?? x, default: () => [] }),
  proposedActions: Annotation({ reducer: (x, y) => y ?? x, default: () => [] }),
  confidence: Annotation({ reducer: (x, y) => y ?? x, default: () => 0 }),
  verification: Annotation({ reducer: (x, y) => y ?? x, default: () => null }),
  errors: Annotation({ reducer: (x, y) => [...(x || []), ...(y || [])], default: () => [] }),
  stepsTaken: Annotation({ reducer: (x, y) => (x || 0) + (y || 1), default: () => 0 }),
  toolCallCount: Annotation({ reducer: (x, y) => (x || 0) + (y || 0), default: () => 0 }),
  correlationId: Annotation({ reducer: (x, y) => y ?? x, default: () => '' }),
  status: Annotation({ reducer: (x, y) => y ?? x, default: () => 'IN_PROGRESS' }),
  summary: Annotation({ reducer: (x, y) => y ?? x, default: () => '' }),
  resultSummary: Annotation({ reducer: (x, y) => y ?? x, default: () => null }),
});

module.exports = { InvestigationState };
