'use strict';

/**
 * Task 15 — Verification & Persistence Detection Enums and Constants
 */

const CHECK_STATUS = Object.freeze({
  PASS: 'PASS',
  FAIL: 'FAIL',
  INCONCLUSIVE: 'INCONCLUSIVE',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
});

const VERIFICATION_STATUS = Object.freeze({
  VERIFIED: 'VERIFIED',
  PARTIALLY_VERIFIED: 'PARTIALLY_VERIFIED',
  FAILED: 'FAILED',
  INCONCLUSIVE: 'INCONCLUSIVE',
  PERSISTENCE_FOUND: 'PERSISTENCE_FOUND',
  PENDING: 'PENDING',
});

const PERSISTENCE_STATUS = Object.freeze({
  NO_PERSISTENCE: 'NO_PERSISTENCE',
  POSSIBLE_PERSISTENCE: 'POSSIBLE_PERSISTENCE',
  PERSISTENCE_FOUND: 'PERSISTENCE_FOUND',
  INCONCLUSIVE: 'INCONCLUSIVE',
});

const RESIDUAL_RISK = Object.freeze({
  NONE: 'NONE',
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  UNKNOWN: 'UNKNOWN',
});

const CHECK_TYPES = Object.freeze({
  OAUTH_APP_STATE: 'OAUTH_APP_STATE',
  ACCESS_TOKEN_STATE: 'ACCESS_TOKEN_STATE',
  ACTIVE_SESSION_STATE: 'ACTIVE_SESSION_STATE',
  SSH_KEY_STATE: 'SSH_KEY_STATE',
  CONNECTED_ACCOUNT_STATE: 'CONNECTED_ACCOUNT_STATE',
  POST_RECOVERY_EVENTS: 'POST_RECOVERY_EVENTS',
  GRAPH_PROJECTION_STATE: 'GRAPH_PROJECTION_STATE',
  SECURITY_SETTINGS_STATE: 'SECURITY_SETTINGS_STATE',
});

const EXPECTED_STATES = Object.freeze({
  REVOKE_OAUTH: 'REVOKED_OR_ABSENT',
  REVOKE_TOKEN: 'INACTIVE_OR_REVOKED',
  TERMINATE_SESSION: 'TERMINATED_OR_INACTIVE',
  REMOVE_SSH_KEY: 'REMOVED_OR_ABSENT',
  DISABLE_INTEGRATION: 'DISABLED',
});

/** Event types occurring post-recovery that indicate potential attacker persistence. */
const SUSPICIOUS_POST_RECOVERY_EVENTS = Object.freeze([
  'OAUTH_GRANTED',
  'SSH_KEY_CREATED',
  'TOKEN_CREATED',
  'SESSION_CREATED',
  'SUSPICIOUS_LOGIN',
  'CREDENTIAL_CREATED',
  'DEVICE_ADDED',
  'SECURITY_SETTING_CHANGED',
]);

/** Audit event actions for the verification lifecycle. */
const VERIFICATION_AUDIT_ACTIONS = Object.freeze({
  VERIFICATION_STARTED: 'VERIFICATION_STARTED',
  VERIFICATION_CHECK_COMPLETED: 'VERIFICATION_CHECK_COMPLETED',
  VERIFICATION_COMPLETED: 'VERIFICATION_COMPLETED',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED',
  VERIFICATION_INCONCLUSIVE: 'VERIFICATION_INCONCLUSIVE',
  PERSISTENCE_DETECTED: 'PERSISTENCE_DETECTED',
  REINVESTIGATION_TRIGGERED: 'REINVESTIGATION_TRIGGERED',
  INCIDENT_RESOLVED: 'INCIDENT_RESOLVED',
  INCIDENT_REMAINED_UNRESOLVED: 'INCIDENT_REMAINED_UNRESOLVED',
});

module.exports = {
  CHECK_STATUS,
  VERIFICATION_STATUS,
  PERSISTENCE_STATUS,
  RESIDUAL_RISK,
  CHECK_TYPES,
  EXPECTED_STATES,
  SUSPICIOUS_POST_RECOVERY_EVENTS,
  VERIFICATION_AUDIT_ACTIONS,
};

